version: '2'
services:
  mst-user-service:
    stdin_open: true
    tty: true
    expose:
     - "8080"
    environment:
        SPRING_PROFILES_ACTIVE: qa
        DB_HOST: 10.202.129.3
        SPRING_REDIS_HOST: 10.202.129.3
    image: <IMAGE_NAME>