version: '2'
services:
  mst-user-service:
    stdin_open: true
    tty: true
    expose:
     - "8080"
    environment:
        SPRING_PROFILES_ACTIVE: qa
    image: <IMAGE_NAME>
  redis:
    tty: true
    image: redis:alpine
    ports:
      - '6379:6379'
    stdin_open: true